# -*- coding: utf-8 -*-
"""LVADSUSR100_Naveen_IA2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Evbcc_4ByI7idLRY6n9_dV0BgxahDO4J
"""

#1


import numpy as np
arr=np.array(rgb_image)
for i in arr:
  result=(i[0]*0.2989)+(i[1]*0.5870)+(i[2]*0.1140))
  print('conversion is : ', result)

#2

import numpy as np
arr=np.array([[2,3,4],[4,5,6],[6,8,9]])
print('mean of the index 0 is :',arr[0].mean())
print('Standard Deviation of index 1 is :',arr[1].std())

#3

import numpy as np
arr=np.array([[[1,2,3],[2,3,5]],[[3,4,6],[7,6,8]]])
new_flatten=arr.flatten()
print(new_flatten)

new_2d=new_flatten.reshape(3,4)
print(new_2d)

#4

#5

import numpy as np
arr=np.array([[1,2,3,4],[3,4,5,np.nan]])
for i in arr:
  result=np.nanmean(i[len(i)-3:len(i)])
  print(i[len(i)-3:len(i)])
  print(result)

#6

#7

import pandas as pd
df=pd.DataFrame(data)
df_two=df[(df['Age'<45])&(df['Department'] !='HR')]
print(df_two[['Name','City']])

#8

#9

employee_data={'Employee':['Alice','Bob','Charlie','David'],
               'Department':['HR','IT','Finance','IT'],
               'Manager':['John','Rechal','Emily','Rachel']}

project_data={'Employee':['Alice','Chatlie','Eve'],
              'Project':['p1','p2','p3']}

import pandas as pd
df1=pd.DataFrame(employee_data)
df2=pd.DataFrame(project_data)
print(df1)
print(df2)

result=pd.merge(df1,df2,on='Employee',how='left')
print(result)



#10
import pandas as pd


data = {
    'Department': ['Electronics', 'Electronics', 'Clothing', 'Clothing', 'Home Goods'],
    'Salesperson': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Sales': [70000, 50000, 30000, 40000, 60000]
}
df = pd.DataFrame(data)


dep_sales = df.groupby('Department')['Sales'].sum()

dep_counts = df['Department'].value_counts()
average_sales_per_salesperson = dep_sales / dep_counts

ranked_departments = average_sales_per_salesperson.sort_values(ascending=False)

print("Average Sales per Salesperson in Each Department:")
print(average_sales_per_salesperson)

print("\nRanked Departments based on Average Sales per Salesperson:")
print(ranked_departments)

